Repository npm/rfcs, pull requests merged in 2019-01, with the labels that each got.

#14 Create 0002-no-caret-prerelease-installs.md
  0008-no-caret-prerelease-installs.md
Labels: :semver-major, cli

#27 Package overrides
  accepted/0009-package-overrides.md
Labels: :under-discussion, cli

#19 Add Monorepo Subdirectory Declaration RFC
  accepted/0010-monorepo-subdirectory-declaration.md
Labels: :ratified, cli, website
