Repository npm/rfcs, pull requests merged in 2020-02, with the labels that each got.

#68 RFC: Multiple Funding Sources
  accepted/0018-multiple-funding-sources.md
Labels: Agenda, Enhancement, Release 6.x, semver:minor

#81 remove --depth from npm update
  accepted/0000-remove-update-depth-option.md
Labels: Agenda, Needs Discussion, Release 7.x

#89 feat: added new issue template for RRFC's
  .github/ISSUE_TEMPLATE/rrfc.md
Labels: Enhancement
